json.title @service.title
json.description @service.description
json.district @service.district
json.created_at @service.created_at
json.category @service.category
json.updated_at @service.updated_at
json.ratings @service.ratings
json.user @service.user
json.average_rating @service.average_rating